# Generated by Django 4.0.5 on 2022-07-08 14:55

from django.db import migrations, models
import samadhiapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('uploadimg', models.ImageField(blank=True, null=True, upload_to=samadhiapp.models.upload_to)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('uploadimg', models.ImageField(blank=True, null=True, upload_to=samadhiapp.models.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Facilitadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('activity', models.CharField(max_length=150)),
                ('bio', models.TextField()),
                ('service', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('uploadimgname', models.ImageField(blank=True, null=True, upload_to=samadhiapp.models.upload_to_name)),
                ('clase', models.ManyToManyField(blank=True, related_name='facilitadores', to='samadhiapp.clases')),
            ],
        ),
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('clase', models.ManyToManyField(blank=True, related_name='alumnos', to='samadhiapp.clases')),
            ],
        ),
    ]
