# Generated by Django 4.0.5 on 2022-06-22 16:50

from django.db import migrations, models
import samadhiapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('samadhiapp', '0003_alter_facilitadores_clase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clases',
            name='uploadimg',
            field=models.ImageField(blank=True, null=True, upload_to=samadhiapp.models.upload_to),
        ),
        migrations.AlterField(
            model_name='facilitadores',
            name='clase',
            field=models.ManyToManyField(blank=True, related_name='facilitadores', to='samadhiapp.clases'),
        ),
        migrations.AlterField(
            model_name='facilitadores',
            name='uploadimg',
            field=models.ImageField(blank=True, null=True, upload_to=samadhiapp.models.upload_to),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='uploadimg',
            field=models.ImageField(blank=True, null=True, upload_to=samadhiapp.models.upload_to),
        ),
    ]
