# Generated by Django 4.0.5 on 2022-06-29 17:38

from django.db import migrations, models
import samadhiapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('samadhiapp', '0004_alter_clases_uploadimg_alter_facilitadores_clase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='clase',
            field=models.ManyToManyField(related_name='alumnos', to='samadhiapp.clases'),
        ),
        migrations.AlterField(
            model_name='facilitadores',
            name='uploadimg',
            field=models.ImageField(blank=True, null=True, upload_to=samadhiapp.models.upload_to_name),
        ),
    ]
