# Generated by Django 4.0.5 on 2022-06-29 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samadhiapp', '0005_alter_alumnos_clase_alter_facilitadores_uploadimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facilitadores',
            old_name='uploadimg',
            new_name='uploadimgname',
        ),
    ]
