# Generated by Django 4.0.5 on 2022-07-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samadhiapp', '0006_rename_uploadimg_facilitadores_uploadimgname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='clase',
            field=models.ManyToManyField(blank=True, related_name='alumnos', to='samadhiapp.clases'),
        ),
    ]
